from pathlib import Path
from mpfb_drape import pipeline

REPO = Path("/home/kubangpawis/dev/GarmentCode/.claude/worktrees/feat+mpfb-drape")
DEFAULT_SIM = REPO / "assets/Sim_props/default_sim_props.yaml"


def test_make_sim_props_has_stats_and_no_optimize():
    props = pipeline.make_sim_props(DEFAULT_SIM)
    cfg = props["sim"]["config"]
    assert cfg["optimize_storage"] is False          # forced off
    assert "material" in cfg and "options" in cfg     # kept from yaml
    stats = props["sim"]["stats"]
    for key in ("fails", "meshgen_time", "face_count", "body_collisions",
                "self_collisions", "sim_time", "fin_frame"):
        assert key in stats                            # init_sim_props structure
    assert "render" in props


import json
import trimesh
import yaml


def test_drape_one_injects_seg_and_returns_record(tmp_path):
    # Use the bundled, COMPLETE mean_all body so the real fit step has full
    # measurements; stub only the GPU sim. Staging into assets/bodies is what
    # PathCofig requires (it reads the body yaml from there at construction).
    bodies = REPO / "assets/bodies"
    body_yaml = bodies / "mean_all.yaml"
    body_obj = bodies / "mean_all.obj"
    seg_extra = bodies / "mean_all_bodyseg.json"  # generated by staging; cleaned up below
    with open(REPO / "assets/design_params/t-shirt.yaml") as f:
        design = yaml.safe_load(f)["design"]

    captured = {}

    def fake_run(paths, props, caching=False):
        # stand in for template_simulation: capture overrides + emit a clean draped obj + stats
        captured["body_seg"] = str(paths.body_seg)
        captured["body_obj"] = str(paths.in_body_obj)
        m = trimesh.creation.box(extents=[0.4, 0.5, 0.2])
        m.apply_translation([0, 1.2, 0])  # in-bounds for the ~1.7 m mean_all body
        m.export(str(paths.g_sim))
        props["sim"]["stats"]["body_collisions"][paths.sim_tag] = 2
        props["sim"]["stats"]["self_collisions"][paths.sim_tag] = 0

    try:
        res = pipeline.drape_one(
            body_yaml, body_obj, design, out_dir=tmp_path / "out",
            bodies_dir=bodies, name="mean_all",
            sim_props_yaml=DEFAULT_SIM, run=fake_run)
        assert res["design"] == "mean_all"
        assert res["body_name"] == "mean_all"
        assert res["verdict"]["passed"] is True, res["verdict"]["reasons"]
        # body_seg points at OUR generated avatar seg, not the bundled ggg:
        assert "mean_all_bodyseg.json" in captured["body_seg"]
        assert json.loads(Path(captured["body_seg"]).read_text())  # valid seg json
    finally:
        seg_extra.unlink(missing_ok=True)
